# python 3
# FROM shankari/e-mission-server:master_2024-02-10--19-38
# Please change once all PR changes are final, so it reads from shankari/e-mission-server
FROM mukuflash03/e-mission-server:image-push-merge_2024-04-30--59-58

VOLUME /plots

ADD docker/environment36.dashboard.additions.yml /

WORKDIR /usr/src/app

RUN /bin/bash -c "source setup/activate.sh && conda env update --name emission --file setup/environment36.notebook.additions.yml"
RUN /bin/bash -c "source setup/activate.sh && conda env update --name emission --file /environment36.dashboard.additions.yml"

ADD docker/start_notebook.sh /usr/src/app/.docker/start_notebook.sh
RUN chmod u+x /usr/src/app/.docker/start_notebook.sh

ADD docker/crontab /usr/src/app/crontab

EXPOSE 8888

CMD ["/bin/bash", "/usr/src/app/.docker/start_notebook.sh"]
